// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AppSession struct {
	ID          uuid.UUID
	Fingerprint json.RawMessage
	IssuedAt    time.Time
	ExpiresAt   time.Time
	JwtID       uuid.UUID
	Revoked     bool
}
