// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	CreateAppSession(ctx context.Context, arg CreateAppSessionParams) error
	GetActiveAppSessionByDeviceID(ctx context.Context, fingerprint string) (GetActiveAppSessionByDeviceIDRow, error)
	RevokeAppSession(ctx context.Context, arg RevokeAppSessionParams) error
}

var _ Querier = (*Queries)(nil)
