{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{- if .Values.serviceAccount.name }}
    {{ .Values.serviceAccount.name }}
  {{- else }}
    {{ include "pluto-backend.fullname" . }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "pluto-backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
