# charts/pluto-backend/templates/swaggerui-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pluto-backend.fullname" . }}-swaggerui
  labels:
    app: {{ include "pluto-backend.name" . }}
    component: swaggerui
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.swaggerui.port }}    # остаётся 8081
      targetPort: http                      # маппим на containerPort:8080
      name: http
  selector:
    app: {{ include "pluto-backend.name" . }}
    component: swaggerui
