// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Manifest struct {
	ID            uuid.UUID
	Version       string
	Icon          string
	Category      string
	Tags          []string
	AuthorName    string
	AuthorEmail   string
	CreatedAt     time.Time
	MetaCreatedAt time.Time
}

type ManifestContent struct {
	ManifestID  uuid.UUID
	Ui          json.RawMessage
	Script      string
	Actions     json.RawMessage
	Permissions []string
	Signature   string
}

type ManifestLocalization struct {
	ManifestID uuid.UUID
	Locale     string
	Key        string
	Value      string
}
