// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	ListManifests(ctx context.Context, arg ListManifestsParams) ([]ListManifestsRow, error)
	SearchManifests(ctx context.Context, arg SearchManifestsParams) ([]Manifest, error)
	SearchManifestsFTS(ctx context.Context, arg SearchManifestsFTSParams) ([]SearchManifestsFTSRow, error)
}

var _ Querier = (*Queries)(nil)
