static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 443
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/auth" }
                          route: { cluster: "auth" }
                        - match: { prefix: "/manifest" }
                          route: { cluster: "manifest" }
                http_filters:
                  - name: envoy.filters.router.jwt_authn
                  - name: envoy.filters.router.router
  clusters:
    - name: auth
      connect_timeout: 0.25s
      type: STATIC
      load_assignment:
        cluster_name: auth
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: auth-service
                      port_value: 8080
    - name: manifest
      connect_timeout: 0.25s
      type: STATIC
      load_assignment:
        cluster_name: manifest
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: manifest-service
                      port_value: 8081
